dist: xenial
language: node_js
node_js:
  - '--lts'
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
branches:
  except:
    - gh-pages
script:
  - yarn typecheck
  - yarn lint
  - yarn test --ci --coverage
  - yarn build
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
